### PR TITLE
revolt-fx new build script

### PR DESCRIPTION
**Pull request by anonim-issue**
Hi, I really liked your library and would like to use it.
My project actively uses TypeSctipt and pixi.js@^7.
When I started your library, I got curse words from the system (I am attaching a screenshot).
I took some assembly tips from pixi3d.

error
image

code 
https://github.com/anonim-issue/revolt-bug-presentation

When replaced with a new assembly, everything works correctly

### CODE REVIEW

**Comment by anonim-issue** [comment]
https://github.com/anonim-issue/revolt-bug-presentation/tree/new-build-revolt branch with new build

**Comment by anonim-issue** [comment]
@bma73 
image

**Comment by bma73** [comment]
@anonim-issue I've pushed an update to the branch. Could you try again?

**Comment by anonim-issue** [comment]
@bma73 Now it works, tested it on several projects

**Comment by anonim-issue** [comment]
Thanks for the work

**Pull request closed without merging**
